Update: Remove visibility: hidden from disabled popup paging buttons (fixes #86)
cgkineo/adapt-hotgrid pull request #88
Opened 2022-08-16 20:57 UTC by swashbuck

Fixes #86

### Update
* Removes 'visibility: hidden' from Hotgrid popup disabled paging buttons

### Testing
1. Add a Hotgrid component to a course.
1. Click on an item to open the Notify popup.
1. The disabled buttons should be visible.

Requires https://github.com/adaptlearning/adapt-contrib-core/pull/221

2022-08-16 21:00 UTC, oliverfoster approved these changes

2022-08-23 17:01 UTC, kirsty-hames requested changes
I've tested this with JAWS and can confirm fixed once [toggleAccessibleEnabled](https://github.com/cgkineo/adapt-hotgrid/blob/b80ff075d09170664b43608922e42f0fd3ff8ece/js/hotgridPopupView.js#L44) has been replaced with `toggleEnabled` as per Hotgraphic Popup https://github.com/adaptlearning/adapt-contrib-hotgraphic/pull/242#issuecomment-1224256837

2022-08-25 15:20 UTC, swashbuck commented
Thanks, all.  I've replaced toggleAccessibleEnabled with toggleEnabled.  Also, some minor code updates for ES6 syntax.

2022-08-25 15:28 UTC, kirsty-hames approved these changes

2022-08-25 20:59 UTC, oliverfoster commented
@joe-allen-89 would you mind releasing this please?

2022-08-25 21:00 UTC, merged